import pyttsx3
friend = pyttsx3.init()
friend.say("Hello,Pankaj ")
friend.runAndWait()
friend.say("I am vs friend")
friend.runAndWait()
friend.say("I have some Word for you")
friend.runAndWait()
friend.say("You are really cute")
friend.say("handsome")
friend.say("tallented")
friend.say("smart")
friend.say("honest")
friend.say("hardworking")
friend.say("lovely")
friend.say("Everyone love with you")
friend.say("I love your smile")
friend.say("I have no words for you")
friend.say("No matterhow much you are praised,it is less")
friend.say("love you Pankaj")
friend.runAndWait()
